### ISSUE TITLE
Domain request: `dmzartchive.illust.bio`

### ISSUE THREAD

**Issue by ArtChivegroup** [Nekidev/illust.bio#3]
# New Subdomain

Subdomain requested: `dmzartchive.illust.bio`

## Description:
Moch Dimas Almahtar is Indonesian musician, music producer, and graphic designer. He is known by his stage names Dimas Hop, ARTCHIVE DMZ, and ARTCHIVE Beat.

### Purpose:
This subdomain will be used to showcase Dimas' portfolio, including his music releases, graphic design work, and any other related content.

### Social Media Links:
- [Instagram](https://www.instagram.com/dmz.artchive?igsh=MTd2ajB6d3BxNDA3Zw==)
- [ARTCHIVE YOUTUBE](https://youtube.com/@artchiveip?si=IZRvYppAH2mnNBlI)
- [Spotify](https://open.spotify.com/artist/5PEF0tNtIxjf0MjVaQzbLN?si=na8ew92pRpygy_1fpzgABw&utm_source=copy-link)

### Contact Information:
- Email: dimasalmactar12@gmail.com
- Phone: +62 89652251871
- Instagram: @dmz.artchive

## Records

| Type | Name | Content | CF Proxy | TTL |
|------|------|---------|----------|-----|
| CNAME | @ | dmzartchive.illust.bio | Proxied | Auto |
| A | @ | 185.199.108.153 | Proxied | Auto |
| A | @ | 185.199.109.153 | Proxied | Auto |
| A | @ | 185.199.110.153 | Proxied | Auto |
| A | @ | 185.199.111.153 | Proxied | Auto |

## Tasks

- [x] I've specified everything I'm going to do with this subdomain
- [x] I've provided enough details to verify that I'm acceptable for the subdomain
- [ ] I've added all the records I want to add to this subdomain (you can modify these later).
- [x] I've read and accepted the [Terms of Use](https://github.com/Nekidev/illust.bio/blob/main/TERMS.md)
